/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCard: typeof import('./src/base/components/card/BaseCard.vue')['default']
    BaseDataTable: typeof import('./src/base/components/table/BaseDataTable.vue')['default']
    BaseHeader: typeof import('./src/base/components/header/BaseHeader.vue')['default']
    BaseIcon: typeof import('./src/base/components/icons/BaseIcon.vue')['default']
    BaseNavigationItem: typeof import('./src/base/components/navigation/BaseNavigationItem.vue')['default']
    BaseStepper: typeof import('./src/base/components/stepper/BaseStepper.vue')['default']
    BaseStepperButtons: typeof import('./src/base/components/stepper/BaseStepperButtons.vue')['default']
    HelloWorld: typeof import('./src/base/components/HelloWorld.vue')['default']
    LogoIcon: typeof import('./src/base/components/icons/LogoIcon.vue')['default']
    NavigationBar: typeof import('./src/base/components/navigation/NavigationBar.vue')['default']
    NavigationItem: typeof import('./src/base/components/navigation/NavigationItem.vue')['default']
    NavigationUserItem: typeof import('./src/base/components/navigation/NavigationUserItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
